name: WebTreeScan
version: 0.1
ResultPath: ./result

SpiderMaxNum: 5 #最大爬虫数量
Spider:
  page_analyze_timeout_second: 300  # 页面分析超时时间，单位秒，暂时无效 功能没加><
  retry: 0                          # 页面访问失败后的重试次数
  Threads: 5                        # Spider请求线程数
                                    #有打算写 无头浏览器扫描方式
  Httpspider:
    domain_headers:
      - domain: '.' #正则
        headers: '{"Cookie": "","User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"}'
    navigate_timeout_second: 5      #请求超时时间
    proxy: ''                       # 代理配置

Downloader: #自动下载功能没写
  Enable: true
whitelistFile : whitelist.txt